'use client'

export type AdminSection =
  | 'dashboard'
  | 'products'
  | 'categories'
  | 'orders'
  | 'site'
  | 'sections'
  | 'gallery'
  | 'testimonials'
  | 'reviews'
  | 'faq'
  | 'newsletter'
  | 'customRequests'
  | 'stockNotifications'
