'use client'

export type AdminSection =
  | 'dashboard'
  | 'analytics'
  | 'products'
  | 'categories'
  | 'bundles'
  | 'orders'
  | 'reviews'
  | 'questions'
  | 'customRequests'
  | 'coupons'
  | 'loyalty'
  | 'blog'
  | 'stories'
  | 'gallery'
  | 'testimonials'
  | 'faq'
  | 'newsletter'
  | 'stockNotifications'
  | 'sections'
  | 'site'
  | 'costs'
  | 'agenda'
  | 'backups'
  | 'emails'
